### ISSUE TITLE
Breaking Change In 2.0.0

### ISSUE THREAD

**Issue by eat-sleep-code** [hieudole/PagedList.Core.Mvc#10]
In prior versions there was an option to suppress the Prev and Next buttons and display Page Numbers Only by using this kind of syntax:

<pager class="history-pager" list="@((IPagedList)ViewBag.PageOfData)" **options="@PagedListRenderOptions.PageNumbersOnly"** asp-controller="Pages" asp-action="History" />

But now, that option seems to have been moved or removed.   What is the equivalent?

**Comment by hieudole** [comment]
It was removed in 2.0.0. There's a new option in version 2.0.1 called Bootstrap4PageNumbersOnly.

**Comment by eat-sleep-code** [comment]
Probably should remove the reference to Bootstrap4 as: 

- What happens when Bootstrap 5 comes out?
- I am not using Bootstrap at all.

**Comment by hieudole** [comment]
They are the built-in options for convenience of using with Bootstrap4, but you can create your own option and use it in the pager.
