### ISSUE TITLE
PagedList.Core.Mvc 2.1.0 appears to be broken in .NET Core 3.0.

### ISSUE THREAD

**Issue by eat-sleep-code** [hieudole/PagedList.Core.Mvc#11]
Perhaps I missed something in my migration to .NET Core 3.0, but all other parts of my page are running flawlessly.

I have the following in my code:

`@if (ViewBag.PageCount > 1)
	{
		<div class="pagination-container">
			<pager class="news-pager" list="@((IPagedList)ViewBag.PageOfData)" options="@PagedListRenderOptions.Bootstrap4PageNumbersOnly" asp-controller="Pages" asp-action="News"  />
		</div>
	}`

The following is output on my page:

`<div class="pagination-container">
			<pager class="news-pager" list="PagedList.Core.PagedList`1[Framework.Models.NewsItem]" options="PagedList.Core.Mvc.PagedListRenderOptions" asp-controller="Pages" asp-action="News">
		</pager></div>`

**Comment by eat-sleep-code** [comment]
@hieudole Not sure if this is related to this from: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio

> Razor Class Library projects that provide UI components for MVC must set the AddRazorSupportForMvc property in the project file:

```
<PropertyGroup>
   <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
</PropertyGroup>
```

**Comment by daver77** [comment]
@eat-sleep-code Did you resolve this issue?

**Comment by eat-sleep-code** [comment]
The latest version seems to solve the issue.   Also make sure the following dependency is also installed in your project: https://www.nuget.org/packages/PagedList.Core/
