### ISSUE TITLE
Specifying PagedListDisplayMode?

### ISSUE THREAD

**Issue by eat-sleep-code** [hieudole/PagedList.Core.Mvc#3]
I am transitioning some code from PagedList.Mvc to PagedList.Mvc.Core.

Now there is the pager HTML helper, what attribute do you use to set the PagedListDisplayMode?

I know I can specify, `options="@PagedListRenderOptions.PageNumbersOnly"` to set the render options.

But, Visual Studio's Intellisense is not giving any hints on how specify the PagedListDisplayMode.

**Comment by hieudole** [comment]
Upgrading VS should help. Closed.
