### ISSUE TITLE
Paging problem

### ISSUE THREAD

**Issue by thecobe** [hieudole/PagedList.Core.Mvc#4]
Hi
here is my question
http://stackoverflow.com/questions/43540613/pagedlist-core-mvc-paging-not-working
Can you help me please?
thanks

**Comment by hieudole** [comment]
Hello,
You've got 404 because your action method FaqSearchResults(int? page, FaqSearch faqSearch) is defined as POST. Remove [HttpPost] attribute on the action will solve the issue.

**Comment by thecobe** [comment]
Hi
thank you very much for your answer
i will try to change my page as soon as possible
Right now i made a roll back
bye
Marco

**Comment by thecobe** [comment]
Hi if i remove [HttpPost] attribute i have this error

Status Code: 400; Bad Request

I have removed [ValidateAntiForgeryToken] attribute too and now it works

thanks

bye

Marco
