### ISSUE TITLE
Sql Server version compatibility

### ISSUE THREAD

**Issue by MCFHTAGENTS** [hieudole/PagedList.Core.Mvc#6]
I think, from reading the internet you have a reliance on SQL Server 2012. I am getting

SELECT [o].[SITE_ID], [o].[ENDPOINT_ID], [o].[ALEXA_TYPE], [o].[CREATED], [o].[CREATED_BY], [o].[DELETED], [o].[DESCRIPTION], [o].[ENABLED], [o].[VALID]
FROM [ALEXA_ENDPOINT] AS [o]
WHERE [o].[ALEXA_TYPE] IN (0, 1) AND ([o].[SITE_ID] = @__id_0)
ORDER BY [o].[DESCRIPTION]
OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY

If I run this code with parameters in place it fails on SQL Server 2008 
http://erikej.blogspot.co.uk/2014/12/a-breaking-change-in-entity-framework.html

Please can you look to make it downgrade successfully

Thanks
Mark

**Comment by hieudole** [comment]
I think this issue is not related to the pager. Closed.
