### ISSUE TITLE
Can it have support for bootstrap 4?

### ISSUE THREAD

**Issue by gitM-iru** [hieudole/PagedList.Core.Mvc#9]
Would you please add bootstrap 4 pagination  support?

So that the `<li>` tag can comes with "page-item" class and `<a>` tag can come with "Page-link" class.
some thing like this.
```
<ul class="pagination pagination-sm">
  <li class="page-item"><a class="page-link" href="#">Previous</a></li>
  <li class="page-item"><a class="page-link" href="#">1</a></li>
  <li class="page-item"><a class="page-link" href="#">2</a></li>
  <li class="page-item"><a class="page-link" href="#">3</a></li>
  <li class="page-item"><a class="page-link" href="#">Next</a></li>
</ul>
```

**Comment by gitM-iru** [comment]
<<ul class="pagination pagination-sm">
  <li class="page-item"><a class="page-link" href="#">Previous</a></li>
  <li class="page-item"><a class="page-link" href="#">1</a></li>
  <li class="page-item"><a class="page-link" href="#">2</a></li>
  <li class="page-item"><a class="page-link" href="#">3</a></li>
  <li class="page-item"><a class="page-link" href="#">Next</a></li>
</ul>>

**Comment by hieudole** [comment]
Yes. It supports Bootstrap 4 by default.
